version: '3'

services:
  myapp-dev:
    image: nginx:latest
    container_name: myapp-dev
    ports:
      - "9090:80"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - myapp-net

  myapp-prod:
    image: nginx:latest
    container_name: myapp-prod
    ports:
      - "90:80"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - myapp-net

networks:
  myapp-net:
    driver: bridge

    